title: "Object 6D Pose Estimation"
log_level: 2
inputs:
    input0:
        source: /dev/video2
        format: jpeg
        width: 1280
        height: 960
        framerate: 30
    input1:
        source: /opt/edgeai-test-data/videos/object_6d_pose_estimation_sample.h264
        format: h264
        width: 1280
        height: 960
        framerate: 30
        loop: True
    input2:
        source: /opt/edgeai-test-data/images/%04d.jpg
        width: 1280
        height: 960
        index: 0
        framerate: 1
        loop: True
models:
    model0:
        model_path: /opt/model_zoo/ONR-6DP-7200-yolox-s-6d-object_pose-640x480
        viz_threshold: 0.8
outputs:
    output0:
        sink: kmssink
        width: 1920
        height: 1080
        overlay-performance: True
    output1:
        sink: /opt/edgeai-test-data/output/output_video0.mkv
        width: 1920
        height: 1080
    output2:
        sink: fakesink
        width: 1280
        height: 720
        port: 8081
        host: 0.0.0.0

flows:
    flow0: [input1,model0,output0,[320,180,1280,720]]